Repository Alzheimer-dinger/BE, pull requests merged in 2025-07, with the labels that each got.

#2 feat: 개발 환경 세팅
  src/main/java/opensource/alzheimerdinger/core/domain/XXX/application/dto/request/XXXRequest.java
  src/main/java/opensource/alzheimerdinger/core/domain/XXX/application/dto/response/XXXResponse.java
  src/main/java/opensource/alzheimerdinger/core/domain/XXX/application/usecase/XXXUseCase.java
  src/main/java/opensource/alzheimerdinger/core/domain/XXX/domain/entity/XXX.java
  src/main/java/opensource/alzheimerdinger/core/domain/XXX/domain/repository/XXXRepository.java
  src/main/java/opensource/alzheimerdinger/core/domain/XXX/domain/service/XXXService.java
  src/main/java/opensource/alzheimerdinger/core/domain/XXX/infra/kafka/consumer/XXXConsumer.java
  src/main/java/opensource/alzheimerdinger/core/domain/XXX/infra/kafka/producer/XXXProducer.java
  src/main/java/opensource/alzheimerdinger/core/domain/XXX/infra/repository/XXXRepositoryImpl.java
  src/main/java/opensource/alzheimerdinger/core/domain/XXX/ui/XXXController.java
  src/main/java/opensource/alzheimerdinger/core/global/common/BaseEntity.java
  src/main/java/opensource/alzheimerdinger/core/global/common/BaseResponse.java
  src/main/java/opensource/alzheimerdinger/core/global/exception/ExceptionAdvice.java
  src/main/java/opensource/alzheimerdinger/core/global/exception/RestApiException.java
  src/main/java/opensource/alzheimerdinger/core/global/exception/code/BaseCode.java
  src/main/java/opensource/alzheimerdinger/core/global/exception/code/BaseCodeInterface.java
  src/main/java/opensource/alzheimerdinger/core/global/exception/code/status/AuthErrorStatus.java
  src/main/java/opensource/alzheimerdinger/core/global/exception/code/status/GlobalErrorStatus.java
  src/main/java/opensource/alzheimerdinger/core/global/exception/code/status/SuccessStatus.java
Labels: enhancement

#9 Feat: 인증 인가 구축
  build.gradle
  src/main/java/opensource/alzheimerdinger/core/domain/user/application/usecase/UserAuthUseCase.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/domain/service/TokenLifecycleService.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/domain/service/UserService.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/ui/AuthController.java
  src/main/java/opensource/alzheimerdinger/core/global/annotation/CurrentUser.java
  src/main/java/opensource/alzheimerdinger/core/global/config/RedisConfig.java
  src/main/java/opensource/alzheimerdinger/core/global/config/SecurityConfig.java
  src/main/java/opensource/alzheimerdinger/core/global/config/WebMvcConfig.java
  src/main/java/opensource/alzheimerdinger/core/global/interceptor/JwtBlacklistInterceptor.java
  src/main/java/opensource/alzheimerdinger/core/global/resolver/CurrentUserArgumentResolver.java
  src/main/java/opensource/alzheimerdinger/core/global/security/ExcludeBlacklistPathProperties.java
  src/main/java/opensource/alzheimerdinger/core/global/security/JwtAuthenticationFilter.java
  src/main/java/opensource/alzheimerdinger/core/global/security/TokenProvider.java
  src/main/resources/application.yml
Labels: enhancement

#8 feat: Kafka Consumer/Producer 설정을 위한 KafkaConfig 클래스 추가
  build.gradle
  src/main/java/opensource/alzheimerdinger/core/CoreApplication.java
  src/main/java/opensource/alzheimerdinger/core/domain/conversation/ui/ConversationController.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/application/dto/request/LoginRequest.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/application/dto/request/SignUpRequest.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/application/dto/response/LoginResponse.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/application/usecase/UserAuthUseCase.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/domain/entity/Role.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/domain/entity/User.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/domain/repository/UserRepository.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/domain/service/UserService.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/ui/AuthController.java
  src/main/java/opensource/alzheimerdinger/core/global/config/KafkaConfig.java
  src/main/java/opensource/alzheimerdinger/core/global/config/SecurityConfig.java
  src/main/java/opensource/alzheimerdinger/core/global/exception/code/status/AuthErrorStatus.java
  src/main/java/opensource/alzheimerdinger/core/global/exception/code/status/GlobalErrorStatus.java
  src/main/java/opensource/alzheimerdinger/core/global/security/ExcludeAuthPathProperties.java
  src/main/java/opensource/alzheimerdinger/core/global/security/JwtAuthenticationFilter.java
  src/main/java/opensource/alzheimerdinger/core/global/security/JwtProperties.java
  src/main/java/opensource/alzheimerdinger/core/global/security/TokenProvider.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: feature

#36 fix: DB 수정에 따른 Consumer 코드 변경
  src/main/java/opensource/alzheimerdinger/core/domain/analysis/application/dto/request/CognitiveReportRequest.java
  src/main/java/opensource/alzheimerdinger/core/domain/analysis/application/dto/request/EmotionAnalysisRequest.java
  src/main/java/opensource/alzheimerdinger/core/domain/analysis/domain/entity/CognitiveReport.java
  src/main/java/opensource/alzheimerdinger/core/domain/analysis/domain/entity/ConversationSession.java
  src/main/java/opensource/alzheimerdinger/core/domain/analysis/domain/entity/EmotionAnalysis.java
  src/main/java/opensource/alzheimerdinger/core/domain/analysis/domain/repository/CognitiveReportRepository.java
  src/main/java/opensource/alzheimerdinger/core/domain/analysis/domain/repository/ConversationSessionRepository.java
  src/main/java/opensource/alzheimerdinger/core/domain/analysis/domain/repository/EmotionAnalysisRepository.java
  src/main/java/opensource/alzheimerdinger/core/domain/analysis/domain/service/CognitiveReportService.java
  src/main/java/opensource/alzheimerdinger/core/domain/analysis/domain/service/EmotionAnalysisService.java
  src/main/java/opensource/alzheimerdinger/core/domain/analysis/infra/kafka/consumer/CognitiveReportConsumer.java
  src/main/java/opensource/alzheimerdinger/core/domain/analysis/infra/kafka/consumer/EmotionAnalysisConsumer.java
  src/main/java/opensource/alzheimerdinger/core/domain/transcript/application/dto/request/TranscriptRequest.java
  src/main/java/opensource/alzheimerdinger/core/domain/transcript/domain/entity/ConversationEntry.java
  src/main/java/opensource/alzheimerdinger/core/domain/transcript/domain/entity/Speaker.java
  src/main/java/opensource/alzheimerdinger/core/domain/transcript/domain/entity/Transcript.java
  src/main/java/opensource/alzheimerdinger/core/domain/transcript/domain/service/TranscriptService.java
  src/main/java/opensource/alzheimerdinger/core/domain/transcript/infra/kafka/consumer/TranscriptConsumer.java
  src/main/resources/application.yml
  src/test/java/opensource/alzheimerdinger/core/domain/analysis/infra/kafka/consumer/CognitiveReportConsumerTest.java
  src/test/java/opensource/alzheimerdinger/core/domain/analysis/infra/kafka/consumer/EmotionAnalysisConsumerTest.java
  src/test/java/opensource/alzheimerdinger/core/domain/transcript/infra/kafka/consumer/TranscriptConsumerTest.java
  src/test/resources/application.yml
Labels: feature, fix

#39 SwaggerAPI 연결 및 세부내용 작성
  build.gradle
  src/main/java/opensource/alzheimerdinger/core/CoreApplication.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/ui/AuthController.java
  src/main/java/opensource/alzheimerdinger/core/global/config/SecurityConfig.java
  src/main/java/opensource/alzheimerdinger/core/global/config/SwaggerConfig.java
  src/main/java/opensource/alzheimerdinger/core/global/config/properties/CorsProperties.java
  src/main/resources/application.yml
Labels: feature

#41 feat: Transcript 도메인에 summary 추가
  src/main/java/opensource/alzheimerdinger/core/domain/transcript/application/dto/request/TranscriptRequest.java
  src/main/java/opensource/alzheimerdinger/core/domain/transcript/domain/entity/SummaryEntry.java
  src/main/java/opensource/alzheimerdinger/core/domain/transcript/domain/entity/Transcript.java
  src/main/java/opensource/alzheimerdinger/core/domain/transcript/domain/service/TranscriptService.java
  src/main/java/opensource/alzheimerdinger/core/domain/transcript/infra/kafka/consumer/TranscriptConsumer.java
  src/main/java/opensource/alzheimerdinger/core/global/security/JwtProperties.java
  src/test/java/opensource/alzheimerdinger/core/domain/transcript/infra/kafka/consumer/TranscriptConsumerTest.java
Labels: feature

#43 Feat: 환자 보호자 기능 및 공통 기능 개발
  src/main/java/opensource/alzheimerdinger/.DS_Store
  src/main/java/opensource/alzheimerdinger/core/CoreApplication.java
  src/main/java/opensource/alzheimerdinger/core/domain/feedback/application/dto/request/SaveFeedbackRequest.java
  src/main/java/opensource/alzheimerdinger/core/domain/feedback/application/usecase/FeedbackUseCase.java
  src/main/java/opensource/alzheimerdinger/core/domain/feedback/domain/entity/Feedback.java
  src/main/java/opensource/alzheimerdinger/core/domain/feedback/domain/entity/Rating.java
  src/main/java/opensource/alzheimerdinger/core/domain/feedback/domain/repository/FeedbackRepository.java
  src/main/java/opensource/alzheimerdinger/core/domain/feedback/domain/service/FeedbackService.java
  src/main/java/opensource/alzheimerdinger/core/domain/feedback/ui/FeedbackController.java
  src/main/java/opensource/alzheimerdinger/core/domain/relation/application/dto/request/RelationConnectRequest.java
  src/main/java/opensource/alzheimerdinger/core/domain/relation/application/dto/request/RelationReconnectRequest.java
  src/main/java/opensource/alzheimerdinger/core/domain/relation/application/dto/response/RelationResponse.java
  src/main/java/opensource/alzheimerdinger/core/domain/relation/application/usecase/RelationManagementUseCase.java
  src/main/java/opensource/alzheimerdinger/core/domain/relation/domain/entity/Relation.java
  src/main/java/opensource/alzheimerdinger/core/domain/relation/domain/entity/RelationStatus.java
  src/main/java/opensource/alzheimerdinger/core/domain/relation/domain/repository/RelationRepository.java
  src/main/java/opensource/alzheimerdinger/core/domain/relation/domain/service/RelationService.java
  src/main/java/opensource/alzheimerdinger/core/domain/relation/ui/RelationController.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/application/dto/request/SignUpRequest.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/application/dto/request/SignUpToGuardianRequest.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/application/dto/response/ProfileResponse.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/application/dto/response/TokenReissueResponse.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/application/usecase/UserAuthUseCase.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/application/usecase/UserProfileUseCase.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/domain/entity/Gender.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/domain/entity/Role.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/domain/entity/User.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/domain/repository/UserRepository.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/domain/service/RefreshTokenService.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/domain/service/TokenBlacklistService.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/domain/service/TokenLifecycleService.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/domain/service/TokenReissueService.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/domain/service/TokenWhitelistService.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/domain/service/UserService.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/ui/AuthController.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/ui/TokenController.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/ui/UserController.java
  src/main/java/opensource/alzheimerdinger/core/global/annotation/RefreshToken.java
  src/main/java/opensource/alzheimerdinger/core/global/config/SecurityConfig.java
  src/main/java/opensource/alzheimerdinger/core/global/config/WebMvcConfig.java
  src/main/java/opensource/alzheimerdinger/core/global/exception/code/BaseCode.java
  src/main/java/opensource/alzheimerdinger/core/global/exception/code/status/GlobalErrorStatus.java
  src/main/java/opensource/alzheimerdinger/core/global/interceptor/JwtBlacklistInterceptor.java
  src/main/java/opensource/alzheimerdinger/core/global/resolver/RefreshTokenArgumentResolver.java
  src/main/java/opensource/alzheimerdinger/core/global/security/JwtAuthenticationFilter.java
  src/main/java/opensource/alzheimerdinger/core/global/security/TokenProvider.java
  src/main/java/opensource/alzheimerdinger/core/global/util/SecureRandomGenerator.java
  src/test/java/opensource/alzheimerdinger/core/domain/feedback/application/usecase/FeedbackUseCaseTest.java
  src/test/java/opensource/alzheimerdinger/core/domain/relation/application/usecase/RelationManagementUseCaseTest.java
  src/test/java/opensource/alzheimerdinger/core/domain/user/application/usecase/UserAuthUseCaseTest.java
  src/test/java/opensource/alzheimerdinger/core/domain/user/application/usecase/UserProfileUseCaseTest.java
Labels: feature

#47 [FEAT] 각 도메인 별 메트릭 계측 추가 & 프로메테우스/그라파나 연동 완료
  Dockerfile
  build.gradle
  docker-compose.yml
  prometheus.yml
  src/main/java/opensource/alzheimerdinger/core/domain/feedback/application/usecase/FeedbackUseCase.java
  src/main/java/opensource/alzheimerdinger/core/domain/relation/application/usecase/RelationManagementUseCase.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/application/usecase/UserAuthUseCase.java
  src/main/java/opensource/alzheimerdinger/core/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: feature

#52 [FEAT] SwaggerAPI 추가 입력
  src/main/java/opensource/alzheimerdinger/core/domain/feedback/ui/FeedbackController.java
  src/main/java/opensource/alzheimerdinger/core/domain/relation/ui/RelationController.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/ui/TokenController.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/ui/UserController.java
Labels: feature
