Repository Alzheimer-dinger/BE, pull requests merged in 2025-08, with the labels that each got.

#58 [FEAT] 이미지 프로필 업데이트 및 저장 로직 구현
  --data-binary
  -H
  .gitignore
  build.gradle
  src/main/java/opensource/alzheimerdinger/.DS_Store
  src/main/java/opensource/alzheimerdinger/core/domain/image/application/dto/request/UpdateProfileImageRequest.java
  src/main/java/opensource/alzheimerdinger/core/domain/image/application/dto/response/UploadUrlResponse.java
  src/main/java/opensource/alzheimerdinger/core/domain/image/application/usecase/ImageUploadUseCase.java
  src/main/java/opensource/alzheimerdinger/core/domain/image/domain/entity/ProfileImage.java
  src/main/java/opensource/alzheimerdinger/core/domain/image/domain/repository/ProfileImageRepository.java
  src/main/java/opensource/alzheimerdinger/core/domain/image/domain/service/ImageService.java
  src/main/java/opensource/alzheimerdinger/core/domain/image/infra/storage/GcsStorageService.java
  src/main/java/opensource/alzheimerdinger/core/domain/image/infra/storage/StorageService.java
  src/main/java/opensource/alzheimerdinger/core/domain/image/ui/ImageController.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/application/dto/response/ProfileResponse.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/application/usecase/UserProfileUseCase.java
  src/main/java/opensource/alzheimerdinger/core/global/config/GcsConfig.java
  src/main/java/opensource/alzheimerdinger/core/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: feature

#62 [FIX] docker compose 및 UserProfileUseCase 수정
  .dockerignore
  .gitignore
  docker-compose.yml
  prometheus.yml
  src/main/java/opensource/alzheimerdinger/core/domain/user/application/usecase/UserProfileUseCase.java
  src/main/resources/application.yml
Labels: fix

#57 Feat: fcm 알림 및 리마인드 기능 구현
  .gitignore
  build.gradle
  src/main/java/opensource/alzheimerdinger/core/CoreApplication.java
  src/main/java/opensource/alzheimerdinger/core/domain/notification/entity/FcmToken.java
  src/main/java/opensource/alzheimerdinger/core/domain/notification/entity/Notification.java
  src/main/java/opensource/alzheimerdinger/core/domain/notification/repository/FcmTokenRepository.java
  src/main/java/opensource/alzheimerdinger/core/domain/notification/repository/NotificationRepository.java
  src/main/java/opensource/alzheimerdinger/core/domain/notification/service/FcmTokenService.java
  src/main/java/opensource/alzheimerdinger/core/domain/notification/service/NotificationService.java
  src/main/java/opensource/alzheimerdinger/core/domain/relation/domain/repository/RelationRepository.java
  src/main/java/opensource/alzheimerdinger/core/domain/reminder/application/dto/request/ReminderSettingRequest.java
  src/main/java/opensource/alzheimerdinger/core/domain/reminder/application/dto/response/ReminderResponse.java
  src/main/java/opensource/alzheimerdinger/core/domain/reminder/application/usecase/ReminderCommandUseCase.java
  src/main/java/opensource/alzheimerdinger/core/domain/reminder/application/usecase/ReminderQueryUseCase.java
  src/main/java/opensource/alzheimerdinger/core/domain/reminder/domain/entity/Reminder.java
  src/main/java/opensource/alzheimerdinger/core/domain/reminder/domain/entity/ReminderStatus.java
  src/main/java/opensource/alzheimerdinger/core/domain/reminder/domain/repository/ReminderRepository.java
  src/main/java/opensource/alzheimerdinger/core/domain/reminder/domain/service/ReminderService.java
  src/main/java/opensource/alzheimerdinger/core/domain/reminder/infra/batch/ReminderBatchJobConfig.java
  src/main/java/opensource/alzheimerdinger/core/domain/reminder/infra/batch/ReminderBatchScheduler.java
  src/main/java/opensource/alzheimerdinger/core/domain/reminder/infra/batch/ReminderItemWriter.java
  src/main/java/opensource/alzheimerdinger/core/domain/reminder/infra/batch/ReminderKeysetItemReader.java
  src/main/java/opensource/alzheimerdinger/core/domain/reminder/ui/ReminderController.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/application/dto/request/LoginRequest.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/application/usecase/UserAuthUseCase.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/domain/service/TokenBlacklistService.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/ui/UserController.java
  src/main/java/opensource/alzheimerdinger/core/global/config/FcmConfig.java
  src/main/java/opensource/alzheimerdinger/core/global/config/properties/FcmProperties.java
  src/main/java/opensource/alzheimerdinger/core/global/security/JwtProperties.java
  src/main/resources/application.yml
  src/test/java/opensource/alzheimerdinger/core/domain/notification/service/FcmTokenServiceTest.java
  src/test/java/opensource/alzheimerdinger/core/domain/notification/service/NotificationServiceTest.java
  src/test/java/opensource/alzheimerdinger/core/domain/reminder/application/usecase/ReminderCommandUseCaseTest.java
  src/test/java/opensource/alzheimerdinger/core/domain/reminder/application/usecase/ReminderQueryUseCaseTest.java
  src/test/java/opensource/alzheimerdinger/core/domain/user/application/usecase/UserAuthUseCaseTest.java
Labels: feature

#69 [FIX] Nginx /grafana/ 서브패스 추가
  .dockerignore
  .gitignore
  docker-compose.yml
  nginx/conf.d/default.conf
  nginx/nginx.conf
Labels: fix

#71 [FEAT] Nginx prometheus 설정
  docker-compose.yml
  nginx/conf.d/default.conf
  nginx/nginx.conf
Labels: feature

#72 [REFACTOR] Nginx cors 설정 수정 진행
  nginx/conf.d/default.conf
  src/main/java/opensource/alzheimerdinger/core/global/config/SecurityConfig.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: refactor

#75 [FEAT] 프로필 수정 로직 구현
  src/main/java/opensource/alzheimerdinger/core/domain/user/application/dto/request/UpdateProfileRequest.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/application/usecase/UpdateProfileUseCase.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/domain/entity/User.java
  src/main/java/opensource/alzheimerdinger/core/domain/user/ui/UserController.java
  src/test/java/opensource/alzheimerdinger/core/domain/user/application/usecase/UpdateProfileUseCaseTest.java
Labels: feature

#79 [FIX] 프로필 업로드 시 받는 fileKey 생성 수정
  src/main/java/opensource/alzheimerdinger/core/domain/image/application/dto/response/UploadUrlResponse.java
  src/main/java/opensource/alzheimerdinger/core/domain/image/application/usecase/ImageUploadUseCase.java
  src/main/java/opensource/alzheimerdinger/core/domain/image/domain/service/ImageService.java
  src/main/java/opensource/alzheimerdinger/core/domain/image/infra/storage/GcsStorageService.java
  src/main/java/opensource/alzheimerdinger/core/domain/image/infra/storage/StorageService.java
Labels: feature, fix

#86 [REFACTOR] 분석 API 일/월 응답 분리 및 월간 엔드포인트 추가
  src/main/java/opensource/alzheimerdinger/core/domain/analysis/application/dto/response/AnalysisDayResponse.java
  src/main/java/opensource/alzheimerdinger/core/domain/analysis/application/dto/response/AnalysisMonthlyResponse.java
  src/main/java/opensource/alzheimerdinger/core/domain/analysis/application/usecase/AnalysisUseCase.java
  src/main/java/opensource/alzheimerdinger/core/domain/analysis/domain/service/AnalysisService.java
  src/main/java/opensource/alzheimerdinger/core/domain/analysis/ui/AnalysisController.java
Labels: refactor

#88 [FEAT] 통합 보고서 평균 통화 시간 Transcript 기반 계산 및 반환 로직 구현
  src/main/java/opensource/alzheimerdinger/core/domain/analysis/domain/service/AnalysisService.java
  src/test/java/opensource/alzheimerdinger/core/domain/analysis/domain/service/AnalysisServiceTest.java
  src/test/java/opensource/alzheimerdinger/core/domain/relation/application/usecase/RelationManagementUseCaseTest.java
Labels: feature

#90 Feature/ops 51
  README.md
Labels: feature
